accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectCreateView,
    ProjectListView,
    ProjectDetailView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models


# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)

    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    assignee = models.ForeignKey(
        "auth.user",
        related_name="tasks",
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            # user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project
from tasks.models import Task
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    # context_object_name = "projects"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tasks"] = Task.objects.filter(assignee=self.request.user)
        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = [
        "name",
        "description",
        "members",
    ]
    success_url = reverse_lazy("list_projects")

tasks/views.py
# from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.urls import reverse_lazy

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = [
        "name",
        "start_date",
        "due_date",
        "project",
        "assignee",
    ]

    success_url = reverse_lazy("show_project")

    # Redirects to the detail page for the
    # instance just created, assuming that
    # the path name is registered
    # def get_success_url(self):
    # return reverse_lazy("model_name_detail", args=[self.object.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    context_object_name = "tasks"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = [
        "name",
        "start_date",
        "due_date",
        "project",
        "assignee",
    ]

    # Redirects to the detail page for the
    # instance just created, assuming that
    # the path name is registered
    def get_success_url(self):
        return reverse_lazy("show_my_tasks", args=[self.object.id])

projects/templates/projects/create.html
<!DOCTYPE html>    <!-- inheritance wasnt working with the tests for some reason SO I removed it from all my templates due to time, however can be readded later-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class ="navigation">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new project</h1>

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create</button>
                    </div>
                </main>
            </body>
        </html>

projects/templates/projects/detail.html
{% load markdownify %}
<!DOCTYPE html>    <!-- inheritance wasnt working with the tests for some reason SO I removed it from all my templates due to time, however can be readded later-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class ="navigation">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>{{ project.name }}</h1>
                <p> {{project.description }} </p>
                <h2> {{ project.task }} </h2>
                <!-- ^ this is probably wrong ^  feature 13 if you need reference to fix later-->

                {{ project.description|markdownify }}
                {% if project.tasks %} <!-- change this too ;o; -->
                    <table>
                        <thead>
                            <tr></tr>
                        </thead>
                    </table>
                {% endif %}
            </div>
        </main>
    </body>
</html>

projects/templates/projects/list.html
<!DOCTYPE html>    <!-- inheritance wasnt working with the tests for some reason SO I removed it & base.html from all my templates due to time, however can be readded later-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class ="navigation">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        <main>
            <div>
                {% if user.is_authenticated %}
                    <h1>My Projects</h1>

                    <p>
                        <a href= "{% url "create_project" %}">Create a new Project!</a>
                        <p>

                            {% if not project_list %}
                                <p>You are not assigned to any projects</p>
                            {% else %}
                                <style>
                                    table, th, td {
                                        border: 1px solid black;
                                    }
                                </style>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Number of tasks</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for anything in project_list %}
                                            <tr>
                                                <td>
                                                    <a href="show_project" > {{ anything }} </a>
                                                </td>
                                                <td> {{ project.task }} </td>
                                                <!--you need the number of tasks here-->

                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--this table does not work properly, come back and fix later, also this is feature 5 if you need reference-->
                            {% endif %}
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/tasks/create.html
<!DOCTYPE html>    <!-- inheritance wasnt working with the tests for some reason SO I removed it/ base.html from all my templates due to time, however can be readded later-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class ="navigation">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "singup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new task</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create</button>
                    </div>
                </main>
            </body>
        </html>

tasks/templates/tasks/list.html
<!DOCTYPE html>    <!-- inheritance wasnt working with the tests for some reason SO I removed it/ base.html from all my templates due to time, however can be readded later-->
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class ="navigation">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "singup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>My Tasks</h1>
                <li>
                    <a href="{% url "create_task" %}">Create a task!</a>
                </li>
                {% if tasks %}
                    <style>
                        table, th, td {
                            border: 1px solid black;
                        }
                    </style>
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Start date</th>
                                <th>End date</th>
                                <th>Is completed</th>
                                <tr>
                                </thead>
                                <tbody>
                                    {% for task in tasks %}
                                        <tr>
                                            <td>{{ task.name }}</td>
                                            <td>{{ task.start_date }}</td>
                                            <td>{{ task.end_date }}</td>
                                            <td>
                                                {% if task.is_completed %}
                                                    <p>Done</p>
                                                {% else %}
                                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="is_completed" value="True">
                                                        <button>Complete</button>
                                                    </form>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                {% else %}
                    <p>You have no tasks</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>